#!/bin/bash

# Load resources

xrdb -merge .Xresources

# Set up an icon tray

trayer \
  --edge bottom \
  --align right \
  --SetDockType true \
  --SetPartialStrut true \
  --expand true \
  --width 5 \
  --transparent true \
  --tint 0x000000 \
  --height 15 &

# Set the background color<

xsetroot -solid black

# Fire up apps

xscreensaver -no-splash &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

if [ -x /usr/bin/gnome-power-manager ] ; then
   sleep 3
   gnome-power-manager &
fi

#xset b off

# eval `gpg-agent --daemon`
# eval `ssh-agent --daemon`

exec xmonad

